dist: xenial 
sudo: false
language: python
python: 
  - "3.7" 
install:
  - cp config.cfg.example config.cfg
  - pip install -r requirements/dev
  - make install
  - pip install codecov

script: make test
after_success:
  - codecov
