categories = {
        "Amning": True,
        "Andre anvendelsesområder": True,
        "Anvendelsesområder": True,
        "Bivirkninger": True,
        "Bloddonor": True,
        "Dispenseringsform": True,
        "Doping": True,
        "Doseringsforslag": True,
        "Egenskaber, håndtering og holdbarhed": True,
        "Farmakodynamik": True,
        "Farmakokinetik": True,
        "Firma": True,
        "Forgiftning": True,
        "Forsigtighedsregler": True,
        "Foto og identifikation": True,
        "Graviditet": True,
        "Hjælpestoffer": True,
        "Indholdsstoffer": True,
        "Instruktioner": True,
        "Interaktioner": True,
        "Kontraindikationer": True,
        "Nedsat leverfunktion": True,
        "Nedsat nyrefunktion": True,
        "Pakninger, priser, tilskud og udlevering": True,
        "Schengen-attest (pillepas)": True,
        "Substitution": True,
        "Tilskud": True,
        "Trafik": True,
        "Typiske alvorlige fejl": True
    }